sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: Ft8nj9eZDjmml1vKRvQ/QI1ibqDMDmDmo+1rIgzifavSmyy5U/C5yrHp5BQVGPybCjpFwY5cM+fLKCIlqeU1z/3jloWb0qee3gVVsjF7UisWZBv4L8ODzvOgCKcta7Yr3I9tqg5+1WDmOzlbRbPJlHKzbdPoeG0+Zdq0gW9ju6FbfoBbbcoQxhWA9RJn8I8BXis136hXU3ynEYmoUMtNAgnyBx5rBuC+i6SSnDnuM3cywUq5KacrvlEB3AGqsrx19Sii7wVNDcv4kvTrFtoDcMUC7ag76qGcvTyNMQrBFPSHn64cmb0Z/h4ab4DoSzOxyjN4B8OwnwEH15hXKISzFOf81fd5F6ZCrJL2YkzjYim8s8gP+QJElrzbPfIVTOFPqCpMUQO2XjvLhiqXybQ4FaeRBt+XztH2aWhdtmK1SjWkjHE8cVZhqvptMHHwtMvD8ybk3YS/y82J6y7l9VbGdL+gLnJF80LCKydUQmb7NogawJN5Xw+EeoCRmyLLLxRzeswfiiG1UeOddGrAw8CCtVdHoWu9vEJ49Tn9AQ0oYPVcrC+JGd2T6tKgmlD29gP8G9u0Ooookdu/3g2nH5KiSgNtQD6q7vkgyOiOOBb0kTEyZQAfsGrMi9cNZCiGXaL9E0ibQ99A9Lh0SMw0YRRSxCTpNy/VURjewo4tuHUFs7A=
branches:
  only:
  - master
