sudo: false
language: ruby
cache: bundler
rvm:
- 2.1.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: nO4ocOiDudxvkeQ/7H7kiJBBw6ef1XoGGh+j17K3B3aQS5Pe6KKZ9BiJf3ez60ktAIh1kbnD0f50XXru2s6JcL1bzMSLx7k+50aVYEqhxdyag/CTc0WFgtu0woIuHWYWl96UhRnreDHc7IE+H+1rPbZgMs3AYR3FzYZyiNi4/PnH7AhU8pvJ7GBiu8fbcKdB0MyNEXlge9SziEJ1Qm0Dl182eI/sFrYXt4H5YKNJrLq+rO3jPp7vzRtu6pvGZzcG6vg4xvbXNJme2VeONJqge3EgfjeLLprUCkgdEA2HncKKXLurB0qL/GNmKVFo/NdYowFHZLno1IbsMsNKVJewuSUdbd6d2MZMf9pUY4K4UJ9ffMhcF8HCJKT4QaNwQe2pkkBiFUKLWJzj+jCQc+BHf72tG0LiTLewuRD6rYqX0v3fzo52ZFiTfQtmBRh0poxerJk0WWOGj+zC377L2QZuBcsxIzvKtmAdQOkXDKPaTldV08LOA/ifW7EQuHumpFlC7YIFQ8QFW2HguZeNnt1HjMdMSHSQkgHWuDEzzL8yyROTt6HeKCZN5uisEafjf4Tc9CKBNfgRGuRagaLsndC+fTXbeW8LcqzzCPaJhPUuWbruHAPjIagoqx9IwcIB9R5d5L+M/v9+vzxBJ4WOS60wbON1IdNhTXEEgP/lw3/hEEA=
branches:
  only:
  - master
dd:
  secure: Ft8nj9eZDjmml1vKRvQ/QI1ibqDMDmDmo+1rIgzifavSmyy5U/C5yrHp5BQVGPybCjpFwY5cM+fLKCIlqeU1z/3jloWb0qee3gVVsjF7UisWZBv4L8ODzvOgCKcta7Yr3I9tqg5+1WDmOzlbRbPJlHKzbdPoeG0+Zdq0gW9ju6FbfoBbbcoQxhWA9RJn8I8BXis136hXU3ynEYmoUMtNAgnyBx5rBuC+i6SSnDnuM3cywUq5KacrvlEB3AGqsrx19Sii7wVNDcv4kvTrFtoDcMUC7ag76qGcvTyNMQrBFPSHn64cmb0Z/h4ab4DoSzOxyjN4B8OwnwEH15hXKISzFOf81fd5F6ZCrJL2YkzjYim8s8gP+QJElrzbPfIVTOFPqCpMUQO2XjvLhiqXybQ4FaeRBt+XztH2aWhdtmK1SjWkjHE8cVZhqvptMHHwtMvD8ybk3YS/y82J6y7l9VbGdL+gLnJF80LCKydUQmb7NogawJN5Xw+EeoCRmyLLLxRzeswfiiG1UeOddGrAw8CCtVdHoWu9vEJ49Tn9AQ0oYPVcrC+JGd2T6tKgmlD29gP8G9u0Ooookdu/3g2nH5KiSgNtQD6q7vkgyOiOOBb0kTEyZQAfsGrMi9cNZCiGXaL9E0ibQ99A9Lh0SMw0YRRSxCTpNy/VURjewo4tuHUFs7A=
